### ISSUE TITLE
New globus group: 	 NIH CFDE Test 1 Mock DCC Submitters

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/security#15]
I'd like to have a add a new globus group: `NIH CFDE Test 1 Mock DCC Submitters`

I see at least ways I'm going to use this:

1. I'd like to give it to my testing team so if they are trying to help a DCC build/troubleshoot their datapackage they can submit it to the test area without me having to get them `NIH CFDE Portal Admin`
2. For DCCs who are having submission tool problems, I could transiently put a DCC person in it, so they could push a known working package (like the HMP one) without polluting their actual submission queue

**Comment by lliming** [comment]
Hi Amanda. There are two parts to adding groups & group-based permissions. The first part is creating the group in Globus. Actually, anyone can do that, it doesn't have to be created by me or a tech team member: you can do it yourself. If you do so, you're automatically an Administrator of the group, and you can invite others.  The second part is assigning a specific permission in DERIVA based on the group's ID. I'm pretty sure that needs to be done by the tech team, and I believe it falls into the category of "things that require a new release." (But I defer to @karlcz to confirm/deny this.) If I'm right about that, then we can set the new permission up in dev & staging very easily and quickly, but getting the new permission set up in production might be something we need to schedule as part of a release, or at least take more care about doing.

Anyway, would you prefer to create the Globus group for this yourself, or would you prefer me to do it for you? I'm ok either way. To create a group yourself, login to the Globus web app (https://app.globus.org/), click the Groups icon on the far left side of the page (or the main menu if using a mobile device), then click "Create new group" in the upper-right corner of the page. Here's a How-to guide: https://docs.globus.org/how-to/managing-groups/

Once the group is created, we need to give the group's ID to the DERIVA team so they can assign the permissions for that group in DERIVA in dev, staging, and production. You can get the ID either by logging out of the CFDE portal and back in and then looking at your user profile, where the group IDs are all displayed, or by looking at the address bar when viewing the group in the Globus web application.  (The group ID will look like this: `1f8a9ec5-9211-11e9-bc6f-0aaa2b1d1516`.)

**Comment by ACharbonneau** [comment]
Neat! I can make it. This is not a super rush so attaching it in Deriva for the next available release is fine. I'll make a deriva issue for it once I have the ID info

**Comment by ACharbonneau** [comment]
Things I did:

1. Made new Globus Group `NIH CFDE Test 1 Mock DCC Submitters`
2. Enrolled it in the registry https://app.nih-cfde.org/chaise/record/#registry/CFDE:group/RID=714
3. And gave it 'data submitter' on Test 1 Mock DCC
4. https://app.nih-cfde.org/chaise/record/#registry/CFDE:dcc/RID=352
5. Added one of my dummy accounts to that globus group
6. Opened incognito, logged in, looks right:
![image](https://user-images.githubusercontent.com/1719360/111678949-345b4280-87f7-11eb-96f8-9853ac4b4a8d.png)

But I'm still locked out of Data Review:
![image](https://user-images.githubusercontent.com/1719360/111679086-52c13e00-87f7-11eb-90eb-78ca22cae99e.png)


I've been submitting to this test DCC for quite a while using my NIH CFDE Portal Admin role, so I know it has baseline functions, so I'm not sure what else I need to do. @karlcz or @lliming any ideas?

**Comment by lliming** [comment]
@karlcz also needs to set permissions inside Deriva, and @DavidKelly999 may also need to do some magic that configures the submission system to acknowledge that new group, I think?

**Comment by ACharbonneau** [comment]
From @karlcz:

> I think I replied to you elsewhere on this but don't see it in the issue conversation.  the flow would be:
> 
> 1. add and link the group in the web ui (seems you have done this)
> 2. get ops team (chicago contingent) to update globus as needed (I'm not sure if they have this automated)
> 3. get ops team (me really) to update the navbar lock permissions to know about new group (I don't have this automated)
> 
> I think you might be able to have the test submitter group members use cfde-submit right away but might run into flow errors if (2) still needs to be done by hand.
> my change in (3) only affects the landing page navbar.  the submitter could actually go to app.nih-cfde.org/chaise/recordset#registry/CFDE:datapackage  and see submissions even if the navbar is locked still.  the registry itself uses its own group/dcc onboarding tables in the policies and so allows access as soon as those tables are adjusted.
> there's another thing like the navbar (3) that gets stale:  a change to registered group-roles for a DCC will affect ACLs on subsequently prepared review catalogs, but existing review catalogs will have ACLs built based on the registry status at the time they were prepared.  I have another reconfiguration step I can do to update all the review catalogs en masse, if we have to retroactively adjust existing review catalogs.

**Comment by ACharbonneau** [comment]
> I think you might be able to have the test submitter group members use cfde-submit right away but might run into flow errors if (2) still needs to be done by hand.

I checked and I can't run flows either

> my change in (3) only affects the landing page navbar.  the submitter could actually go to app.nih-cfde.org/chaise/recordset#registry/CFDE:datapackage  and see submissions even if the navbar is locked still.  the registry itself uses its own group/dcc onboarding tables in the policies and so allows access as soon as those tables are adjusted.


This does not seem to be true. I can't get the submission page, or load a specific page I should have access to:
![image](https://user-images.githubusercontent.com/1719360/112069350-1157c800-8b42-11eb-9530-a983368c3823.png)

![image](https://user-images.githubusercontent.com/1719360/112069300-f84f1700-8b41-11eb-97b6-84192d3c1eb0.png)

**Comment by karlcz** [comment]
OK, I see part of the issue is the onboarded group record was
incompletely filled in.  The same group UUID needs to be
pasted into two fields:

  ID: a05338ad-8816-11eb-a3d7-815208c210f7
  Webauthn Id: https://auth.globus.org/a05338ad-8816-11eb-a3d7-815208c210f7

it was present in ID but the second field just had the prefix
(https://auth.globus.org/) which is already filled in when you go to
edit the form.

I just changed it, so you should see different web UI behavior now.

**Comment by ACharbonneau** [comment]
Oh! That makes sense. And it does make going to direct links work. 

@DavidKelly999 or @NickolausDS could you help me with:

> 2. get ops team (chicago contingent) to update globus as needed (I'm not sure if they have this automated)

**Comment by ACharbonneau** [comment]
Globus is updated. I think now I just need @karlcz to: 

> 3. get ops team (me really) to update the navbar lock permissions to know about new group (I don't have this automated)
